# Generated by Django 5.2 on 2025-04-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='code',
        ),
        migrations.AddField(
            model_name='otp',
            name='session_id',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
    ]
